# Generated by Django 4.2.26 on 2025-12-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь проекта',
                'verbose_name_plural': 'Пользователи проекта',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='BbDetail',
            fields=[
                ('bb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bboard.bb', verbose_name='Объявление')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Деталь объявления',
                'verbose_name_plural': 'Детали объявлений',
            },
        ),
        migrations.CreateModel(
            name='BbRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(verbose_name='Оценка (1-5)')),
                ('rated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.projectuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка объявления',
                'verbose_name_plural': 'Оценки объявлений',
                'unique_together': {('bb', 'user')},
            },
        ),
        migrations.AddField(
            model_name='bb',
            name='rated_by',
            field=models.ManyToManyField(related_name='rated_boards', through='bboard.BbRating', to='bboard.projectuser', verbose_name='Оценившие пользователи'),
        ),
        migrations.AddField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='bb',
            name='tags',
            field=models.ManyToManyField(related_name='boards', to='bboard.tag', verbose_name='Теги'),
        ),
    ]
