# Generated by Django 4.2.26 on 2025-12-27 13:21

import bboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(validators=[bboard.models.validate_positive_price], verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='BbImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bbs/images/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание фото')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bboard.bb')),
            ],
        ),
        migrations.CreateModel(
            name='BbFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Параметр (напр. Цвет)')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bboard.bb')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
