# Generated by Django 4.2.26 on 2025-12-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_price_bbimage_bbfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание рубрики'),
        ),
        migrations.AlterField(
            model_name='bbfeature',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bboard.bb', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='bbfeature',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Параметр'),
        ),
    ]
