# Generated by Django 4.2.26 on 2025-12-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
