# Generated by Django 4.2.26 on 2025-12-28 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_rubric_description_alter_bbfeature_bb_and_more_squashed_0005_projectuser_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbrating',
            name='rating_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Оценка (1-5)'),
        ),
    ]
